sudo: false
dist: bionic
language: python
matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.7
          env: TOXENV=py38
          install:
            sudo add-apt-repository -y ppa:deadsnakes && sudo apt-get update && sudo apt-get install -y --no-install-recommends python3.8-dev python3.8-distutils && python --version && pip install tox
        - python: 3.7
          env: TOXENV=py37,lint,pypi-description,coverage-report
install: pip install tox
script: tox
