sudo: false
dist: bionic
language: python
matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8-dev
          env: TOXENV=py38
        - python: 3.7
          env: TOXENV=py37,lint,pypi-description,coverage-report
install: pip install tox
script: tox
